### ISSUE TITLE
[1.19.2] mod is breaking... nightvision...

### ISSUE THREAD

**Issue by Bass2style** [shutdoor/nightvision_enchant-forge#2]
Hello,

i added your mod in my pack, and it's breaking NightVision overall effect.
giving NV effect with /effect give or using third party mods (Everlasting Abilities for example) doesn't work correctly.

i have no logs or something, because it seems to not leave traces in logs.

i'm using the version 0.0.1 of your mod on forge 43.1.30.
removing your mod fix nightvision issues.

have a nice day.

**Comment by shutdoor** [comment]
Hello,

I have looked into this issue and have found the problem. This will be in fixed version 0.0.2, and is waiting for review on Curseforge.

Note: This issue was the same with the 1.18.2 version and has been fixred on both.

Thank you so much for reaching out to get this fixed.
