### ISSUE TITLE
1.20.1 Update Request

### ISSUE THREAD

**Issue by Zorro8183** [shutdoor/nightvision_enchant-forge#3]
I loved your nightvision enchantment for 1.19.2 as it was very handy and useful but now I would like it for 1.20.1 so I can continue using it. do you think it would be possible to get your nightvision enchantment for 1.20.1 please? also I still use forge.

**Comment by Gamemassa** [comment]
I agree. This would be really helpful.

**Comment by shutdoor** [comment]
I am sorry this took so long. I've gotten this updated to 1.20.1. This is for Neo Forge & Forge.
